//##########################################################################
//#                                                                        #
//#                            CLOUDCOMPARE                                #
//#                                                                        #
//#  This program is free software; you can redistribute it and/or modify  #
//#  it under the terms of the GNU General Public License as published by  #
//#  the Free Software Foundation; version 2 of the License.               #
//#                                                                        #
//#  This program is distributed in the hope that it will be useful,       #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
//#  GNU General Public License for more details.                          #
//#                                                                        #
//#          COPYRIGHT: EDF R&D / TELECOM ParisTech (ENST-TSI)             #
//#                                                                        #
//##########################################################################

#ifndef CC_ASCII_SAVE_DIALOG_HEADER
#define CC_ASCII_SAVE_DIALOG_HEADER

//GUIs generated by Qt Designer
#include <ui_saveAsciiFileDlg.h>

//! Dialog for configuration of ASCII files saving sequence
class AsciiSaveDlg : public QDialog, public Ui::AsciiSaveDialog
{
    Q_OBJECT

public:

	//! Default constructor
    AsciiSaveDlg(QWidget* parent=0);

	//! Destructor
    virtual ~AsciiSaveDlg();

	//! Returns whether columns names should be be saved in header
	bool saveColumnsNamesHeader() const;

	//! Returns whether the number of points should be saved in header
	bool savePointCountHeader() const;

	//! Returns separator
	uchar getSeparator() const;

	//! Returns coordinates precision
	int coordsPrecision() const;

	//! Returns SF precision
	int sfPrecision() const;

	//! Returns whether SF(s) and color should be swapped
	bool swapColorAndSF() const;

protected slots:

	//! Saves dialog state to persistent settings
	void acceptAndSaveSettings();

protected:

	//! Inits dialog state from persistent settings
	void initFromPersistentSettings();

};

#endif //CC_ASCII_SAVE_DIALOG_HEADER

