//##########################################################################
//#                                                                        #
//#                            CLOUDCOMPARE                                #
//#                                                                        #
//#  This program is free software; you can redistribute it and/or modify  #
//#  it under the terms of the GNU General Public License as published by  #
//#  the Free Software Foundation; version 2 of the License.               #
//#                                                                        #
//#  This program is distributed in the hope that it will be useful,       #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
//#  GNU General Public License for more details.                          #
//#                                                                        #
//#          COPYRIGHT: EDF R&D / TELECOM ParisTech (ENST-TSI)             #
//#                                                                        #
//##########################################################################
//
//*********************** Last revision of this file ***********************
//$Author:: dgm                                                            $
//$Rev:: 1792                                                              $
//$LastChangedDate:: 2011-02-14 22:29:04 +0100 (lun., 14 févr. 2011)      $
//**************************************************************************
//
#ifndef CC_PLY_OPEN_DIALOG
#define CC_PLY_OPEN_DIALOG

//GUIs generated by Qt Designer
#include <ui_openPlyFileDlg.h>

//! Dialog for configuration of PLY files opening sequence
class PlyOpenDlg : public QDialog, public Ui::PlyOpenDlg
{
    Q_OBJECT

public:
    PlyOpenDlg(QWidget* parent=0);

protected slots:
    void testBeforeAccept();

signals:
    void fullyAccepted();

};

#endif
