#ifndef CC_RECENTER_CLOUD_DIALOG
#define CC_RECENTER_CLOUD_DIALOG

#include <QDialog>

//GUIs generated by Qt Designer
#include <ui_shiftAndScaleCloudDlg.h>

//! Dialog for selection of cloud center
class ccShiftAndScaleCloudDlg : public QDialog, public Ui::ShiftAndScaleCloudDlg
{
    Q_OBJECT

public:

	//! Default constructor
	/** \param P first point position
		\param diagonal cloud bounding box diagonal (or 0 to ignore)
		\param parent mother widget
	**/
    ccShiftAndScaleCloudDlg(const double* P, double diagonal=0.0, QWidget* parent=0);

	//! Sets displayed shift
	void setShift(double x, double y, double z);

	//! Returns shift
	void getShift(double& x, double& y, double& z) const;

	//! Sets displayed scale
	void setScale(double scale);

	//! Returns scale
	double getScale() const;

	//! Whether to show or not the warning about non pertinent shift information
	void showWarning(bool state);

	//! Whether shift should be applied to all files
	bool applyAll() const { return m_applyAll; }

	//! Whether to show dialog items related to scale
	void showScaleItems(bool state);

protected slots:

	//! Analyzes the clicked button
	void onClick(QAbstractButton* button);

protected:

	//! Whether shift should be applied to all files
	bool m_applyAll;


};

#endif