//##########################################################################
//#                                                                        #
//#                CLOUDCOMPARE PLUGIN: LAS-IO Plugin                      #
//#                                                                        #
//#  This program is free software; you can redistribute it and/or modify  #
//#  it under the terms of the GNU General Public License as published by  #
//#  the Free Software Foundation; version 2 of the License.               #
//#                                                                        #
//#  This program is distributed in the hope that it will be useful,       #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
//#  GNU General Public License for more details.                          #
//#                                                                        #
//#                   COPYRIGHT: Thomas Montaigu                           #
//#                                                                        #
//##########################################################################

#ifndef CC_LAS_OPEN_DIALOG
#define CC_LAS_OPEN_DIALOG

#include "LasFields.h"

// GUIs generated by Qt Designer
#include <ui_lasopendialog.h>

// system
#include <string>
#include <vector>

// CCCoreLib
#include <CCGeom.h>
#include <ccLog.h>

//! Dialog to choose the LAS fields to load
class LasOpenDialog : public QDialog, public Ui::LASOpenDialog {
  Q_OBJECT

public:
  //! Default constructor
  explicit LasOpenDialog(QWidget *parent = nullptr);

  void setInfo(int versionMinor, int pointFormatId, uint64_t numPoints);

  void setAvailableScalarFields(const LasField::Vector &scalarFields);

  void setHasColors(bool state);

  void filterOutNotChecked(LasField::Vector &scalarFields);

  bool loadColors() const;

protected:
  bool isChecked(const LasField &lasScalarField) const;
};

#endif // CC_LAS_OPEN_DIALOG
