name: CloudCompareDev
channels:
  - conda-forge
dependencies:
  - eigen=3.4.*
  - ffmpeg=4.4.*
  - ninja
  - pcl=1.13.*
  - pdal=2.4.*
  - qt=5.15.8
  - xerces-c=3.2.*
  - zlib=1.2.*
  - laszip=3.4.*
