name: CloudCompareDev
channels:
  - conda-forge
dependencies:
  - ninja
  - qt=5.15.*
  - eigen=3.4.*
  - boost=1.84.*
  - pcl=1.14.*
  - ffmpeg=6.1.*
  - xerces-c=3.2.*
  - zlib=1.2.*
  - laszip
  - clang-format==18.*
