.TH ccViewer 1 "February 23 2018"
.SH NAME
ccViewer \- light 3d viewer
.SH SYNOPSIS
.B ccViewer
.RI "files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ccViewer
command.
.PP
\fBccViewer\fP is a light 3d viewer accompaigning CloudCompare.
Press the left mouse button, to rotate your 3d data model in the viewer.
For built-in help, press the F1 key.
.SH SEE ALSO
.BR CloudCompare (1).
.br
