#pragma once

//##########################################################################
//#                                                                        #
//#                CLOUDCOMPARE PLUGIN: LAS-IO Plugin                      #
//#                                                                        #
//#  This program is free software; you can redistribute it and/or modify  #
//#  it under the terms of the GNU General Public License as published by  #
//#  the Free Software Foundation; version 2 of the License.               #
//#                                                                        #
//#  This program is distributed in the hope that it will be useful,       #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
//#  GNU General Public License for more details.                          #
//#                                                                        #
//#                   COPYRIGHT: Thomas Montaigu                           #
//#                                                                        #
//##########################################################################

#include "LasDetails.h"
#include "LasScalarField.h"
#include "LasExtraScalarField.h"

// GUI generated by Qt Designer
#include <ui_lasopendialog.h>

// system
#include <string>
#include <vector>

// CCCoreLib
#include <CCGeom.h>
#include <ccLog.h>

//! Dialog to choose the LAS fields to load
class LasOpenDialog : public QDialog, public Ui::LASOpenDialog
{
    Q_OBJECT

  public:
    //! Default constructor
    explicit LasOpenDialog(QWidget *parent = nullptr);

    void setInfo(int versionMinor, int pointFormatId, int64_t numPoints);

    void setAvailableScalarFields(const std::vector<LasScalarField> &scalarFields,
                                  const std::vector<LasExtraScalarField> &extraScalarFields);

    void filterOutNotChecked(std::vector<LasScalarField> &scalarFields,
                             std::vector<LasExtraScalarField> &extraScalarFields);

    bool isChecked(const LasScalarField &lasScalarField) const;

    bool isChecked(const LasExtraScalarField &lasExtraScalarField) const;
};
