# This workflow creates a .tar.gz archive
# with CloudCompare source code, including submodules
# and should thus be suitable to be used to build CloudCompare.
name: Create Source Bundle


on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-tar-gz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: CloudCompare
          submodules: true

      - name: Create tarball
        # Note  `--exclude-vcs` is only available on GNU's tar
        run: tar --exclude-vcs -zcvf CloudCompare-${{ github.ref_name }}.tar.gz CloudCompare/

      - name: Create Sha256 Sum
        run: sha256sum CloudCompare-${{ github.ref_name }}.tar.gz > CloudCompare-${{ github.ref_name }}.tar.gz.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CloudCompare-${{ github.ref_name }}.tar.gz
            CloudCompare-${{ github.ref_name }}.tar.gz.sha256sum
